# Generated by Django 4.1.9 on 2023-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reference', models.CharField(max_length=200, verbose_name='reference')),
                ('was_donated', models.BooleanField(default=False)),
                ('donated_by', models.IntegerField(null=True)),
                ('quantaty', models.IntegerField()),
                ('list_control_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DonationListControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('closed', models.BooleanField()),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlaceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(max_length=300, verbose_name='meta_keywords')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=600, verbose_name='description')),
                ('category', models.CharField(max_length=200, verbose_name='category')),
                ('attributes', models.CharField(max_length=200, verbose_name='attributes')),
                ('image', models.CharField(max_length=100, verbose_name='image')),
                ('reference', models.CharField(max_length=200, verbose_name='reference')),
                ('product_link', models.CharField(max_length=100, verbose_name='product_link')),
                ('expired_date', models.CharField(max_length=10, verbose_name='expired_date')),
                ('price_from', models.FloatField(verbose_name='price_from')),
                ('price_to', models.FloatField(verbose_name='price_to')),
                ('marketplace', models.CharField(max_length=200, verbose_name='marketplace')),
                ('persuasive_text', models.CharField(max_length=500, null=True, verbose_name='persuasive_text')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='name')),
                ('birthday', models.PositiveIntegerField(default=0, null=True, verbose_name='birthday')),
                ('nationality', models.CharField(max_length=200, verbose_name='nationality')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
