# Generated by Django 4.1.9 on 2023-05-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationListControl',
        ),
    ]
