# Generated by Django 4.2 on 2023-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reference', models.CharField(max_length=200, verbose_name='reference')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlaceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.CharField(max_length=300, verbose_name='meta_keywords')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=600, verbose_name='description')),
                ('category', models.CharField(max_length=200, verbose_name='category')),
                ('attributes', models.CharField(max_length=200, verbose_name='attributes')),
                ('image', models.CharField(max_length=100, verbose_name='image')),
                ('reference', models.CharField(max_length=200, verbose_name='reference')),
                ('product_link', models.CharField(max_length=100, verbose_name='product_link')),
                ('expired_date', models.CharField(max_length=10, verbose_name='expired_date')),
                ('price_from', models.FloatField(verbose_name='price_from')),
                ('price_to', models.FloatField(verbose_name='price_to')),
                ('marketplace', models.CharField(max_length=200, verbose_name='marketplace')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.DeleteModel(
            name='GoodAfter',
        ),
    ]
