# Generated by Django 4.1.9 on 2023-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_donationlistcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationListControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('closed', models.CharField(default='False', max_length=6)),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
