# Generated by Django 4.2 on 2023-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_donationlist_marketplaceproducts_delete_goodafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationlist',
            name='quantaty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
