# Generated by Django 4.1.9 on 2023-05-25 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_donationlistcontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(default='Nao informado', max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(default='000000-000', max_length=9, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='Nao informado', max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, verbose_name='cnpj'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(default='NA', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_juridico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.IntegerField(default=0, verbose_name='num'),
        ),
        migrations.AlterField(
            model_name='donationlistcontrol',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
