# Generated by Django 4.1.9 on 2023-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_user_birthday_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_juridico',
            new_name='is_juridic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num',
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='block'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='NA', max_length=2, verbose_name='state'),
        ),
    ]
