# Generated by Django 4.1.9 on 2023-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_donationlist_quantaty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationlist',
            name='name',
        ),
        migrations.AddField(
            model_name='donationlist',
            name='donated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donationlist',
            name='was_donated',
            field=models.BooleanField(default=False),
        ),
    ]
